name: Front Lint

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev

jobs:
    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: ["14", "16", "18"]
        defaults:
            run:
                working-directory: front
        steps:
            -
                name: Checkout
                uses: actions/checkout@v3
            -
                name: Setup Node
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node-version }}
            -
                name: Install dependencies
                run: |
                    npm update
                    npm i -g html-validate
            -
                name: Lint (html-validate)
                run: |
                    html-validate $(git ls-files '*.html')
